config de jacoco

diff --git a/.github/workflows/build_pourJDK_11_hotspot.yml b/.github/workflows/build_pourJDK_11_hotspot.yml
--- a/.github/workflows/build_pourJDK_11_hotspot.yml
+++ b/.github/workflows/build_pourJDK_11_hotspot.yml
@@ -24,3 +24,18 @@ jobs:
         run:  chmod +x ./gradlew
       - name: Build & test and compute JaCoCo reports
         run: ./gradlew build #jacocoTestReport
+  build-test:
+      name: Build & Test
+      runs-on: ubuntu-latest
+      steps:
+        - uses: actions/checkout@v4     # checkout the repo
+        - run: npm ci                   # install packages
+        - run: npm test                 # run tests (configured to use jest-junit reporter)
+
+        - name: Test Report
+          uses: dorny/test-reporter@v2
+          if: success() || failure()    # run this step even if previous step failed
+          with:
+            name: JEST Tests            # Name of the check run which will be created
+            path: reports/jest-*.xml    # Path to test results
+            reporter: jest-junit        # Format of test results
